version: '3'
services:
  # search engine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    container_name: elasticsearch
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - -Ehttp.cors.allow-credentials=true
    user: elasticsearch
    ports:
      - "9200:9200"
  # elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:3.2.3
    container_name: dejavu
    ports:
     - "1358:1358"
    links:
      - elasticsearch
